### ISSUE TITLE
Link to linkedIn pointing to a non existing profile

### ISSUE THREAD

**Issue by duksis** [nikazawila/nikazawila.com#1]
I get a "profile not found" page when I click on the [link index.html#L24](https://github.com/nikazawila/nikazawila.com/blob/master/index.html#L24).

I really like your hame page - nice work! :+1:

**Comment by nikazawila** [comment]
@duksis hey, yeah... I'm working on that. Got my account hacked :(
But thanks for pinging me!

**Comment by duksis** [comment]
oh - closing this as thats a known issue
